app/src/main/java/net/gaast/giggity/ScheduleViewActivity.java
tools/lowlands_html_parser.pl

patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer )

spelling fixes

---

app/src/main/res/values-fr/strings.xml

I just started trying to actually build under Debian Sid (it still fails), and noticed I missed some backslashes...

Fix french strings (unescaped single quote)

---

app/src/main/res/raw/menu.json

Looks like we'll only get an ICS this year… but at least it works fine.

Add FOSSASIA 2018

---

app/src/main/res/raw/menu.json

Linux event tuebix 2018

---

app/src/main/res/raw/menu.json

GUADEC is happening soon, would be nice to have this years schedule right in the list.

Update GUADEC information for 2018

---

app/src/main/res/raw/menu.json

add PrivacyWeek 2018

---

app/src/main/res/raw/menu.json

Request to add the conference Config Management Camp 2019 schedule to be listed
Signed-off-by: Toshaan Bharvani <toshaan@vantosh.com>

add CfgMgmtCamp 2019 to the event list

---

app/src/main/res/values-fr/arrays.xml
app/src/main/res/values-fr/strings.xml

Some better French words and typos fixed
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

Updated fr (French) translation

---

menu/jdll_2019.json

Not sure the ICS will work again, time will tell.

Add JDLL 2019

---

menu/rml_13.json

We now have an ICS for the schedule :-)

Add RML 13

---

menu/froscon_2019.json

Add FrOSCon 2019

---

menu/debconf19.json

https://debconf19.debconf.org/

Add DebConf19 to the menu

---

menu/diwokiki_2019.json

Hi, @Wilm0r - as promised, here comes the separate entry for the other chain of events.

Entry for Digitale Woche Kiel im Kitz (organized by kielux)

---

menu/cccamp19_main_rooms_only.json

Add CCCamp 2019 main schedule

---

menu/sotm_2019.json
menu/sotm_2019_academic_track.json

`ci/menu-ci.py` worked. Hope you can merge this PR :)

Added State of the Map 2019

---

menu/datenspuren_2019.json

Same as #130 with fixed non-rectangular icon. In case @Wilm0r is around tomorrow ;-)

Datenspuren 2019 (fixed)

---

menu/linuxday_at_2019.json

2019-10-19 - dornbirn/vorarlberg/austria/europe

linuxday.at

---

menu/privacyweek_2019.json

Please add privacyweek 2019 to the list of conferences

add privacyweek 2019

---

menu/alchimie_13.json

Probably only useful for me but who knows ;-)

Add Alchimie 13 demoparty

---

menu/pycon_fr_2019.json

Unable to test due to SSL error on Android 4 though.

Add PyCon FR 2019

---

menu/capitole_du_libre_2019.json

Again I can't fetch the xml directly on Android 4 but I tested a local copy and it works.

Add Capitole du Libre 2019

---

app/src/main/res/values-cs/arrays.xml
app/src/main/res/values-cs/strings.xml
menu/installfest_2020.json

Added Czech translation for this excellent app and InstallFest 2020 to menu

Add Czech translation

---

menu/kielux_2020.json
menu/kielux_LPD_2020.json

Hi! 
Kielux will start in about 2 weeks from now. 
Could these two events be included into Giggity, please?

Kieler Open Source und Linux Tage / Kieler Linux Presentation Day 2020.2

---

menu/vcfb_2020.json

Add the Vintage Computing Festival Berlin 2020

Add VCFB 2020

---

menu/minidebconfindia2021.json

Add MiniDebConf India 2021. @Wilm0r  Please comment if I need to change anything.

Add MiniDebConf India 2021

---

menu/libreplanet_2021.json

Add LibrePlanet 2021

---

menu/sotm_2021.json

Sorry that we're a little bit late this year, but it would be really great if this could be merged soon :)

Add State of the Map 2021

---

menu/entreelibre2.json

Add Entrée Libre 2

---

menu/datenspuren_2021.json

Just in time. As always. Thank you.

[Best-Before: 2021-09-20] Add Datenspuren 2021

---

menu/sfscon_2021.json

Add information about South Tyrol Free Software Conference 2021

Add SFScon 2021

---

menu/matomocamp_2021.json

Thanks for the great app that already helped me in the past with large events.
I hope the version number is correct, I wasn't quite sure how to create it.

add MatomoCamp

---

menu/rc3_2021.json

Just for the record as the event is already started.

Add rC3: NOWHERE 2021

---

menu/jdll_2022.json

Add JDLL 2022

---

menu/libreplanet_2022.json

An initial version of the .ics file is online now at the specified URL. We'll be updating it soon so that it contains info for all of our talks. The conference starts this Saturday.
Thanks : )

Add LibrePlanet 2022

---

menu/glt22.json

Two-day conference about open source / free software / open hardware platforms in Austria/Graz with talks, workshops and information booths

Introduce GLT22

---

menu/emf2022.json

Electromagnetic Fields is happening. See https://www.emfcamp.org/

Add Electromagnetic Fields 2022 (EMF2022) to the Giggity list

---

menu/installfest_2022.json

Hello, I would like to ask for add installfest 2022 to menu. Thnak you

Add Installfest 2022

---

menu/hope_2022.json

Add HOPE 2022

---

menu/linuxday_at__2022.json

for the event "linuxday.at" at 24.9.2022 in Vorarlberg/Austria

linuxday.at 2022

---

menu/pycon_es_2022.json

Added a new entry for the PyCon conference in Spain

Added new entry for PyConES 2022

---

menu/capitole_du_libre_2022.json

It's back \o/
Schedule isn't available yet.

Add Capitole du Libre 2022

---

menu/pgdayparis_2023.json

Add pgDay Paris 2023

---

menu/libreplanet_2023.json

Hi,
Could you please add this LibrePlanet 2023 schedule metadata to Giggity?
Thanks! : )

Add LibrePlanet 2023

---

menu/jdll_2023.json

Hi! This MR adds the 2023 edition of the JdLL event.

Add JdLL 2023

---

menu/cloudland_2023.json

Thanks for this great project!

Add CloudLand 2023

---

menu/opensouthcode_2023.json

Add Opensouthcode 2023, June 9 and 10 in Málaga (Spain)

Add Opensouthcode 2023

---

menu/gpn21.json

`tools/menu-ci.py -b add_GPN21` was happy, so I assume everything should be fine

Add GPN21 (21. GulaschProgrammierNacht)

---

menu/cccamp23_main_rooms_only.json

Add CCCamp23

---

menu/parisweb_2023.json
menu/parisweb_workshops_2023.json

There are actually two ICS files, one for talks and one for workshops…

Add Parisweb 2023

---

menu/kielux_2023.json
menu/kielux_LPD_2023.json

Hi! 
Please add this year's Kielux to Giggity :)
Greetings from Kiel :boat: :wave:

Add Kielux Events 2023

---

menu/debconf23.json

I didn't see @EdwardBetts had already added this. Here's some more data.

Some more metadata for DebConf23

---

menu/linuxday_at__2023.json

for linuxday.at
at sol/earth/europe/austria/vorarlberg/dornbirn

add linuxday_at__2023

---

menu/hacklu_2023.json

Add hack.lu 2023

---

menu/sfscon_2023.json

Add SFSCON23, a significant event that will take place on November 10th and 11th, 2023, in South Tyrol.

add SFSCON23 event

---

menu/pyladiescon_2023.json

Add PyLadiesCon 2023

---

menu/bibliocon24.json

Add BiblioCon 2024 to the menu

---

menu/spathum24.json

schedule.xml not jet published

added Spatial Humanities 2024 schedule

---

menu/sotm_eu_2024.json

This is basically the same as last year. Could you please merge it before 19th? Sorry for being so close to the conference dates.

Add State of the Map Europe 2024

---

menu/sotm_2024.json
tools/menu-ci.py

Same as always: a hourly updated merged schedule from https://sotm.osmz.ru/sotm2024.html
Also fixing a small deprecation in the ci script.

State of the Map 2024

---

menu/kielux_2024.json
menu/kielux_lpd_2024.json

Hi, @Wilm0r - it's that time of the year again :) 
Could you please add our event to the giggity list of events?
Have a great week!

Add Kieler Open Source und Linuxtage 2024

---

menu/linuxday_at__2024.json

add linuxday_at__2024

---

menu/datenspuren_2024.json

Add Datenspuren 2024

---

menu/sfscon_2024.json

Add SFSCON 2024 conference entry.

Add SFSCON 2024

---

menu/libreoffice_libocon_2024.json

LibreOffice conference next week

Add LibreOffice Conference (LibOCon) 2024

---

menu/mrmcd_2024.json

added mrmcd2024 event in Darmstadt, Germany

added mrmcd2024

---

menu/capitole_du_libre_2024.json

Lately add CDL 2024 to menu, scheduled as usual in few days in Toulouse (France).

menu: Add Capitole du Libre 2024

---

menu/everything_open_2025.json

this is the new incarnation of Linux Conf AU

add everything open 2025

---

menu/sstic_2025.json

Couldn't test here, Android 5 only and it says it's empty…

Add SSTIC 2025

---

menu/jdll_2025.json

Icon probably won't work, we only accept PNGs, right?

Add JdLL 2025

---

menu/passthesalt_2025.json

Schedule has been published.
Not sure about the coordinates, can't find which building exactly ont he campus is used.

Add Pass The SALT 2025

---

menu/oat25.json

Adding OAT25 to the menu for Giggity.

Add OAT25 to the menu

---

menu/wikimania_2025.json

Better late than never \o/ lol
Untested :D lol

Add Wikimania 2025

---

menu/akademy_2025.json

The annual event of the KDE community

Add Akademy 2025

---

menu/esc_2k25.json

Always used Giggity when going at international events... now that we have our XML it's time for us to be present! :)
Thank you very much in advance.

Add End Summer Camp {21} (aka 2K25)

---

menu/fsl2025.json

Add Festa do Software Livre 2025, Porto, Portugal

[2025-10-03] Add FSL2025 

---

menu/ietf124.json

The meeting agenda will be published on the coming Friday.

[2025-11-01] Add IETF124
