Wilm0r/giggity

app/src/main/java/net/gaast/giggity/BlockSchedule.java
This makes UI bit nicer when tent names are reasonable length.
Ideally the width should be based on the longest tent name string length (with a max limit) but for now this quick fix improves the UI substantially for longer names (eg. LCA2017).
=> Make the tent name column wider

app/src/main/java/net/gaast/giggity/Schedule.java, giggity.iml
FOSSASIA's open event JSON format contains information about rooms, icon and other web links which has to be added separately for the formats like pentabarf along with sessions.
Please see this issue for reference https://github.com/Wilm0r/giggity/issues/14
App could be tested for this API end point https://open-event-dev.herokuapp.com/api/v1/events/266?include=sessions,microlocations
See the endpoints's response here http://jsonviewer.stack.hu/#http://open-event-dev.herokuapp.com/api/v1/events/266?include=sessions,microlocations .
I have modified app so it automatically fetches the information of locations, sessions and icon's link from this endpoint itself.
=> Adding support for FOSSASIA open event JSON format

app/src/main/res/raw/menu.json
Preview:
The icon doesn't look great on a dark background, but it's what we have...
=> Add DebConf17

app/src/main/java/net/gaast/giggity/EventDialog.java, app/src/main/java/net/gaast/giggity/Schedule.java
This includes speakers and a weblink in the shared information.
The weblink is a newly introduced concept as is supposed to represent the URL where the event is accessible on the web.
I would have prefered to call this `URL` but the `url` field already fulfills a different role.
This new field is only parsed from Pentabarf files, but should be generalizable.
(I am willing to implement it for the other formats)
=> Also share speakers and weblinks

app/src/main/res/raw/menu.json
ICS misses the CALNAME, so it appears with the URL as name, but at least
it's quite short.
=> Add JDLL 2018 (Journées du Logiciel Libres)

app/src/main/res/raw/menu.json
Added 35C3 to the event list. There is a (temporary, hopefully) error with `ci/menu-ci.py`, due to the fact that the wiki for the 2018 event is not public yet and requires authorisation:
EDIT: now the wiki link is accessible, I made an empty commit to re-trigger the CI
```
$ ./ci/menu-ci.py 
Base ref: master
New: 35th Chaos Communication Congress
Fetching https://fahrplan.events.ccc.de/congress/2018/Fahrplan/schedule.xml
Fetching https://events.ccc.de/congress/2018/wiki/index.php/Main_Page
Fetching https://events.ccc.de/
Unchanged: Augsburger Linux-Infotag 2017 (fixed)
Unchanged: LibrePlanet 2017
Unchanged: Opensouthcode 2017
Unchanged: TUEBIX 2017
Unchanged: SHA2017
Unchanged: GUADEC 2018
Unchanged: DebConf17
Unchanged: FrOSCon 2017
Unchanged: PyConFR 2017
Unchanged: LinuxDays 2017 …
```
=> Added 35C3

ci/menu-ci.py
The script `ci/menu-ci.py` requires features only available in Python 3.6, which is not available by default on every distributions (e.g. in Debian it's part of `testing`).
This could be changed to allow lower version numbers, but until then it would be good to break early so the user won't have to look up what's wrong from the exception, and figure out themselves that the Python version is not recent enough.
I am not changing the hashbang to `#!/usr/bin/env python3.6` because that would also stop from using newer versions
=> Enforce python 3.6 early in CI tests

app/src/main/res/raw/menu.json
This also archives the old "Linux.conf.au 2018" to the correct URL's. Currently they are pointing to the linux.conf.au host whereas they should point to 2018.linux.conf.au. The new linux.conf.au 2019 stuff could equally point to linux.conf.au, but it works even better with 2019.linux.conf.au, because in the future there will of course be a 2020 conference.
=> Add Linux.conf.au 2019

menu/installfest_2019.json
I know we've sent PR at the last moment, but be so kind and merge json for Installfest. It's Czech conference about Linux and open-source technologies which takes place on March 2–3. Thank you (and thank you for giggity, it's great app).
=> Add Installfest 2019 to menu

menu/ietf104.json
The conference happens in Prague and starts this weekend.
The schedule suffers a bit from #96, but is well usable within. (Don't get distraught by the first view – the event starts at Saturday with a hackathon block entry, the later days are the ones where I need giggity to keep track of where to be when).
=> Add IETF104 to events

menu/lit_2019.json
The LIT was included in Giggity for the 2017 installment. In 2018, we unfortunately were too late in submitting the pull request. We hope that it'll work again for 2019. :-)
The linked schedule is not yet accessible, but will be soon.
Thank you for your efforts in maintaining Giggity. :-)
=> Add LIT 2019

menu/tuebix_2019.json
Things done:
Results:
```bash
$ ./ci/menu-ci.py 
Base ref: HEAD
Unchanged: FOSSASIA 2018
Unchanged: JDLL 2018
Unchanged: LibrePlanet 2018
Unchanged: NLUUG Spring 2018
Unchanged: PHP Tour Montpellier 2018
Unchanged: T&#xFC;bix 2018
Unchanged: GUADEC 2018
Unchanged: Rencontres Mondiales du Logiciel Libre 2018
Unchanged: PromCon 2018
Unchanged: PrivacyWeek 2018
Unchanged: Forum PHP 2018
Unchanged: Capitole du Libre 2018
Unchanged: RML 12
Unchanged: 35c3 - main rooms only
Unchanged: 35c3 - new and merged
Unchanged: linux.conf.au 2019
Unchanged: FOSDEM 2019
Unchanged: CfgMgmtCamp 2019 Ghent
Unchanged: Installfest 2019
Unchanged: LibrePlanet 2019
Unchanged: IETF 104 Prague
Unchanged: Augsburger Linux-Infotag 2019
Unchanged: Journées du Logiciel Libre 2019
Unchanged: RML 13
Unchanged: …
```
=> Add the Tübix 2019

README.md
Since all conference schedules I added to or used giggity recently used Pretalx, you might want to add it to your README.
=> Added Pretalx to README

README.md
Since Python 2 is discontinued very soon (https://pythonclock.org), you might want to switch to Python 3 for all parts of your project. This PR just changes the QR code generation advice in the README.
=> Switch to python3 for QR code generation

menu/oat19.json
Adding Open-Access-Tage 2019, the annual German-speaking conference on open access to scholary publications.
See
* http://open-access-tage.de/2019
* https://twitter.com/oatage
=> Add Open-Access-Tage 2019

menu/ubucon_europe_2019.json
tested with ci/menu-ci.py
Ubucon Europe will happen between 10-13 oct 2019 in Sintra (Portugal).
Would be nice to be listed in the menu.
Thanks
=> add Ubucon Europe 2019

menu/oss_eu_2019.json
Combined shedule.
Stupid sched.com puts a "X-WR-CALDESC:Event Calendar" in the ICS so the conf gets renamed…
=> Add OSSEU+Linux Embedded Conference Europe

menu/36c3_main_rooms_only.json
Rooms are checked against last year's c3nav as this year's not public yet.
=> Add 36C3 main rooms

menu/bibtag20.json
Add Bibliothekartag 2020 to menu which uses a Pentabarf XML created by https://github.com/UB-Mannheim/bibtag-scheduler
=> Add Bibliothekartag 2020 to menu

app/src/main/AndroidManifest.xml
This attribute change allows using schedules that are hosted on non-ssl enabled websites. Currently Android 9+ forbids this without an explicit permission.
Re: [stackoverflow](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted) and [attribute documentation](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic).
=> Allow schedules hosted on http websites

menu/hope_2020.json
HOLD: URL is temporary, final URL should be available at the end of the week.
Tested, works even on my Android 4 tablet, for once.
=> WIP: Add HOPE 2020

menu/froscon_2020.json
Just noticed FrOSCon is this week-end :)
Removed the map links, hopefully we can add them back next year.
=> Add FrOSCon 2020

menu/fosdem_2021.json
Much simpler than usual since we won't need to locate rooms physically
this year.
=> Add FOSDEM 2021

menu/fossasia_2021.json
Room names are URLs so not best visually but it works.
=> Add FOSSASIA 2021

menu/kielux_2021.json, menu/kielux_LPD_2021.json
Hi @Wilm0r !
Kielux will start soon! This year's online event features 22 talks, 10 workshops and a Software Freedom Breakfast.
I've added our ics file links to the repository.
Greetings from Kiel!
=> Add Kielux 2021 / LPD21.2 (online events)

menu/jres_2022.json
We don't need the `id` field anymore for ICS, right?
=> Add JRES 2022

app/src/main/java/net/gaast/giggity/ScheduleUI.java
When refreshing a schedule for a custom URL, `tz` is null and and a `NullPointerException` is thrown.
=> Check for null timezone when loading schedule.

menu/jres_2022.json
The image is on a Mastodon instance, should be stable enough.
=> JRES 2022: Add icon

menu/bibtag22.json
I am having some troubles to add the json file from another location directly, but hope this will work fine from the menu here. The pentabarf file works fine. However, updating a schedule where the pentabarf file is added directly seems not yet to work in the current version, because the fix https://github.com/Wilm0r/giggity/commit/9c404210fa9524c7caab3a209fb21a3c26b21311 is not yet part of the released version.
=> Add Bibliothekskongress 2022

menu/bornhack_2022.json
Add [BornHack 2022](https://bornhack.dk/bornhack-2022/). The [program](https://bornhack.dk/bornhack-2022/program/events/) times is not published yet, so the frab file is not filled out with the schedule.
=> add BornHack 2022

menu/froscon_2022.json
Based on the 2020 json with dates and links adjusted.
=> Add Froscon 2022

menu/sotm_2022.json
The schedule on https://pretalx.com/sotm2022/ is missing the academic track talks (on Sunday in Auditorium B, see https://2022.stateofthemap.org/programme/#general_Sunday), because the academic talks are managed in a separate pretalx instance (https://pretalx.com/state-of-the-map-2022-academic-track/ vs. https://pretalx.com/sotm2022/). For this reason, we maintain a merged schedule xml during the conference days available at https://sotm.osmz.ru/2022.xml
=> Update source of State of the Map 2022 schedule: adds missing academic talks

menu/oat22.json
I created a skeleton of the schedule (manually) as an XML file and updated it with the abstracts from the website. The icon is from twitter, but I needed to add an alpha layer (hope this works now).
=> Add OAT22 to the menu

menu/Kielux_LPD_2022.json, menu/kielux_2022.json, menu/kielux_LPD_2022.json
Hi! This patch adds our Kielux Linux conference and the preceding Kielux Linux Presentation Day to Giggity.
The events are from September 15 to 17 2022.
=> Add Kielux / Kielux Linux Presentation Day 2022

menu/nixcon2022.json
Adds [NixCon 2022](https://2022.nixcon.org/) to the menu
=> Add NixCon 2022

menu/bibliocon23.json
This conference was previously named "Bibliothekartag" or "Bibliothekskongress" and therefore this is the continuation of bibtag20.json and bibtag22.json.
=> Add BiblioCon 2023

menu/lit_2023.json
It seems that the link should go to the xml version, not the json version, This PR fixes the mistake.
=> Link to xml file of frab export

menu/fossy_2023.json
FOSSY hasn't published a schedule in XML format. The JSON format used by the FOSSY schedule isn't supported by giggity. Switch to using the ICS version of the schedule instead.
=> Switch FOSSY 2023 to use ICS

menu/fossy_2023.json
Reads a version of the schedule in XML that has been generated from the JSON version of the schedule.
The XML version is being regenerated regularly.
This gives more detail that the ICS version.
=> FOSSY 2023: Use schedule in XML converted from the JSON version

menu/froscon_2023.json
Based on the 2022 json with dates and links adjusted.
=> Add Froscon 2023

menu/bornhack_2023.json
Add [BornHack 2023](https://bornhack.dk/bornhack-2023/). The [program](https://bornhack.dk/bornhack-2023/program/events/) times is not published yet, so the frab file is not filled out with the schedule.
=> Add BornHack 2023

menu/grcon23.json
Noticed a bit late this was an option; would be very grateful if merged!
=> Add GNU Radio Conference 2023 in Tempe, Arizona, USA

menu/seagl_2023.json
I noticed they use OSEM which does provide the URL and links to Giggity explicitly, let's add it officially :-)
=> Add SeaGL 2023

menu/lit_2024.json
Add event for Augsburger Linux Info-Tag 2024
=> Add event for LIT2024

menu/jdll_2024.json
Seems previous years used Brussel's timezone for some reason… Luckily it's the same as Paris :-D
=> Add JdLL 2024

menu/opensouthcode_2024.json
Add Opensouthcode 2024, June 21 and 22 in Málaga (Spain)
=> Add OpenSouthCode 2024

menu/foss4g_europe_2024.json, menu/foss4g_europe_2024_full.json
The current version has only the main event schedule and no speaker names. The new one, sourced [from here](https://sotm.osmz.ru/tartu2024.html), merges main event, workshops, birds of feather, all side events, and OGC Innovation Days into one.
I have also added locations for all venues.
=> Better FOSS4G Europe 2024 schedule

menu/oat24.json
Add a menu entry for the Open-Access-Tage 2024.
=> Add OAT24 to the menu

menu/wikimania_2024.json
This adds the schedule for https://wikimania.wikimedia.org/wiki/2024:Wikimania.
Largely inspired from the configuration file for last year.
=> Add Wikimania 2024

menu/moca2024_it.json
This PR adds the schedule for the 2024 edition of MOCA - Metro Olografix Camp
=> menu: added MOCA 2024 schedule

menu/ubuntu_summit_2024.json, tools/ggt.sh
Plus a small fix in `tools/ggt.sh`
One thing to note, Android (13) doesn't seem to open ggt.gaa.st by default, it says something about the link not being verified so I assume this is something you need to do somewhere. However you can manually enable this in the app settings to still test this.
=> Add Ubuntu Summit 2024

menu/ietf121.json
It's in 2 weeks time, so not sure if that makes sense still, or whether I'd better keep the file somewhere else and disseminate through QR codes.
=> Add IETF121

menu/foss4g_2024.json
It's on 2-6 December, so should be fine. The official schedule once again is done by EventFahrplan, ugh.
=> Add FOSS4G 2024

menu/38c3.json
38C3 Fahrplan changes happen frequently and often last-minute. The 30 minute value is copied from last year's 37C3, which apparently went without issues.
The server currently doesn't support `If-None-Match` properly, which is why CI will fail.
I'm proposing this as a PR anyway, so we can merge as soon as either
1) the issue is fixed server-side or
2) the admins approve this PR (in which case the CI should be ignored imho)
=> 38C3: set refresh_interval to 30 minutes

.gitignore, menu/foss4g_europe_2025.json, pyproject.toml
This adds an entry for FOSS4G Europe 2025 conference in Mostar. As usual, I've set up schedule merging.
Also I've updated `.gitignore` for some Python developer by-products, and added `pyproject.toml` if you don't mind, so one can do `uv run tools/menu-ci.py` and not deal with looking up dependencies.
=> FOSS4G Europe 2025

menu/debconf25.json
The logo is 404 currently, but should become available after https://salsa.debian.org/debconf-team/public/websites/dc25/-/merge_requests/50 is merged (and the homepage refreshed)
=> Add DebConf25

menu/why_2025.json
The WHY2025 program was moved to https://program.why2025.org/
=> Correct schedule URL for WHY2025 and add links.
